# Site settings
author: Steven Testa
title: Testa Software
email: steve@testasoftware.com
description: ""
url: "http://testasoftware.com"
baseurl: ""
gravatar_url: "http://www.gravatar.com/avatar/fa0158d5d8c2025ccd4d55cefa30d387.png"
#subscribe_rss: 

# GitHub settings
github_user: stesta
github_repo_url: https://github.com/stesta

# Disqus Comments
disqus_short_name: testasoftware-steve
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-31584220-1

# Build settings
markdown: kramdown
kramdown: 
  input: GFM
permalink: /steve/blog/:title
gems:
- jekyll-sitemap
