# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 10
language: 'en-us'
baseurl: /

# Website info
title: Testa Software
description: The personal and professional home of Steve Testa
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
logo_dark: 
favicon: /assets/images/favicon/favicon.png
production_url: https://testasoftware.com/

# Social info
navigation: True
subscribers: False 
twitter: steven_testa 
facebook: steven.testa 
github: stesta
disqus: True
disqus_shortname: testasoftware-steve
google_analytics: UA-31584220-1

permalink: /:title

plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
