title: λ Testa -> Software
email: steve@testasoftware.com
description: >- 
  The personal and professional home of Steve Testa
baseurl: "" 
url: "https://testasoftware.com"
logo: /assets/images/aboutme/steve-med.jpg
disqus: testasoftware-steve
google_analytics: UA-31584220-1
keywords: [machine learning, ai, software development, programming]
permalink: /:categories/:year-:month-:day-:title/
copyright: >
  © Testa Software 2018. All rights reserved.

# Theme Settings
accent_image: /assets/images/nn.jpg
accent_color: rgb(95,75,139)

paginate:      5
paginate_path: '/blog/:num/'

author:
  name:  Steve
  email: steve@testasoftware.com
  picture: /assets/images/aboutme/steve-med.jpg
  about: |
    I am a developer, consultant, entrepreneur and self described foosball champion. I like to blog occasionally about technology, code, trends and the community (obligatory: **all opinions are my own**).  
  social:
    github: stesta
    twitter: steven_testa
    facebook: steven.testa
    email: steve@testasoftware.com

collections:
  projects:
    permalink: /projects/:path/
    output:    true

defaults: 
  - scope: 
      type: posts
    values: 
      comments: true

hydejack:
  post_addons: [about]
  project_addons: [other]

# Build settings
markdown: kramdown

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

kramdown:
  footnote_backlink:   '&#x21a9;&#xfe0e;'
  math_engine:         mathjax
  math_engine_opts:
    preview:           true
    preview_as_code:   true

compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed